// license:GPLv3+

#include "plugins/MsgPlugin.h"
#include "plugins/VPXPlugin.h"
#include "plugins/ScriptablePlugin.h"

#include "common.h"
#include "Scorbit.h"

#include <string>

using std::string;

namespace Scorbit {

LPI_IMPLEMENT_CPP

static MsgPluginAPI* msgApi = nullptr;
static VPXPluginAPI* vpxApi = nullptr;
static ScriptablePluginAPI* scriptApi = nullptr;
static uint32_t endpointId = 0;
static unsigned int getVpxApiId = 0;
static unsigned int getScriptApiId = 0;

///////////////////////////////////////////////////////////////////////////////
// Settings - sourced from vpinball.ini [Plugin.Scorbit]
//
// 'encryptedKey' is the shared "vpin" provider provisioning secret (the same
// for every user - NOT per user). It is encrypted with Scorbit's encrypt_tool
// and meant to be shipped as the default below. Users never need their own;
// the per-machine device key is auto-generated by the SDK and persisted to
// deviceKeyFile in the pref dir.

MSGPI_STRING_VAL_SETTING(setProvider, "provider", "Provider",
   "Scorbit provider id", false, "vpin", 64);
MSGPI_STRING_VAL_SETTING(setEnv, "environment", "Environment",
   "production or staging", true, "production", 32);
MSGPI_STRING_VAL_SETTING(setKey, "encryptedKey", "Encrypted provider key",
   "Shared 'vpin' provisioning key (encrypted). Same for all users.", true, "", 2048);
MSGPI_STRING_VAL_SETTING(setKeyFile, "deviceKeyFile", "Device key file",
   "Per-machine key filename, relative to the pref dir", false, "scorbit_device.key", 256);
MSGPI_STRING_VAL_SETTING(setUuid, "installUuid", "Install UUID",
   "Optional fixed install id; empty = SDK-derived", true, "", 64);
MSGPI_INT_VAL_SETTING(setLog, "logLevel", "Log level",
   "0 quiet, 1 info, 2 debug", true, 0, 2, 1);
MSGPI_INT_VAL_SETTING(setMid, "machineIdOverride", "Machine id override",
   "Testing only: non-zero overrides the table's DoInit machine id (e.g. 4379 for the SDK staging demo)", true, 0, 2000000000, 0);

ScorbitConfig GetPluginConfig()
{
   ScorbitConfig c;
   c.provider = setProvider_Get();
   c.environment = setEnv_Get();
   c.encryptedKey = setKey_Get();
   c.deviceKeyFile = setKeyFile_Get();
   c.installUuid = setUuid_Get();
   c.logLevel = setLog_Get();
   c.machineIdOverride = setMid_Get();
   return c;
}

///////////////////////////////////////////////////////////////////////////////
// Scriptable interface exposed to table VBScript as CreateObject("Scorbit")

PSC_CLASS_START(ScorbitObj, ::Scorbit::Scorbit)
   // --- Legacy ScorbitIF surface (so existing tables port 1:1) ---
   PSC_FUNCTION4(bool, DoInit, int, string, string, string)
   PSC_FUNCTION0(void, StartSession)
   PSC_FUNCTION1(void, ForceAsynch, bool)
   PSC_FUNCTION5(void, StopSession, double, double, double, double, int)
   PSC_FUNCTION6(void, StopSession2, double, double, double, double, int, bool)
   PSC_FUNCTION1(void, SetGameMode, string)
   PSC_FUNCTION7(void, SendUpdate, double, double, double, double, int, int, int)
   PSC_FUNCTION8(void, SendUpdateAsynch, double, double, double, double, int, int, int, bool)
   PSC_FUNCTION1(void, DoTimer, int)
   PSC_FUNCTION0(void, Callback)
   PSC_FUNCTION1(string, GetName, int)
   PSC_PROP_R(bool, SessionActive)
   PSC_PROP_R(bool, NeedsPairing)
   PSC_PROP_R(bool, Enabled)
   PSC_PROP_W(bool, UploadLog)
   // --- New, clean, cross-platform additions ---
   PSC_FUNCTION0(string, GetPairDeeplink)
   PSC_FUNCTION0(string, GetPairCode)
   PSC_FUNCTION1(string, GetClaimDeeplink, int)
   PSC_FUNCTION2(bool, GenerateQRCode, string, string)
   PSC_FUNCTION0(bool, TakeNewlyPaired)
   PSC_FUNCTION0(int, TakeNewlyClaimedPlayer)
PSC_CLASS_END()

///////////////////////////////////////////////////////////////////////////////
// Plugin entry points

MSGPI_EXPORT void MSGPIAPI ScorbitPluginLoad(const uint32_t sessionId, MsgPluginAPI* api)
{
   msgApi = api;
   endpointId = sessionId;
   LPISetup(endpointId, msgApi);
   LOGI("Scorbit plugin loading"s);

   getVpxApiId = msgApi->GetMsgID(VPXPI_NAMESPACE, VPXPI_MSG_GET_API);
   msgApi->BroadcastMsg(endpointId, getVpxApiId, &vpxApi);

   getScriptApiId = msgApi->GetMsgID(SCRIPTPI_NAMESPACE, SCRIPTPI_MSG_GET_API);
   msgApi->BroadcastMsg(endpointId, getScriptApiId, &scriptApi);

   msgApi->RegisterSetting(endpointId, &setProvider);
   msgApi->RegisterSetting(endpointId, &setEnv);
   msgApi->RegisterSetting(endpointId, &setKey);
   msgApi->RegisterSetting(endpointId, &setKeyFile);
   msgApi->RegisterSetting(endpointId, &setUuid);
   msgApi->RegisterSetting(endpointId, &setLog);
   msgApi->RegisterSetting(endpointId, &setMid);

   auto classLambda = [](ScriptClassDef* scd) { scriptApi->RegisterScriptClass(scd); };
   RegisterScorbitObj(classLambda);

   ScorbitObj_SCD->CreateObject = []() -> void* {
      return new ::Scorbit::Scorbit(msgApi, endpointId, vpxApi);
   };

   scriptApi->SubmitTypeLibrary(endpointId);
   scriptApi->SetCOMObjectOverride("Scorbit", ScorbitObj_SCD);

   const ScorbitConfig c = GetPluginConfig();
   LOGI("CreateObject(\"Scorbit\") registered. provider="s + c.provider
      + " env=" + c.environment
      + " key=" + (c.encryptedKey.empty() ? "MISSING (Scorbit will stay disabled)"s
                                           : ("present (" + std::to_string(c.encryptedKey.size()) + " chars)"))
      + " machineIdOverride=" + std::to_string(c.machineIdOverride));
}

MSGPI_EXPORT void MSGPIAPI ScorbitPluginUnload()
{
   LOGI("Scorbit plugin unloading"s);
   if (scriptApi) {
      scriptApi->SetCOMObjectOverride("Scorbit", nullptr);
      auto classLambda = [](ScriptClassDef* scd) { scriptApi->UnregisterScriptClass(scd); };
      UnregisterScorbitObj(classLambda);
   }
   if (msgApi) {
      msgApi->ReleaseMsgID(getVpxApiId);
      msgApi->ReleaseMsgID(getScriptApiId);
   }
   vpxApi = nullptr;
   scriptApi = nullptr;
   msgApi = nullptr;
}

}
